name: Build ocr2txt EXE

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build EXE with PyInstaller
      run: |
        pyinstaller --onefile --add-data "ocr2txt/tesseract;tesseract" --add-data "ocr2txt/poppler;poppler" ocr2txt/ocr2txt.py

    - name: Upload EXE as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ocr2txt_exe
        path: dist/ocr2txt.exe
